{% set name = "napari-graph" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-graph-{{ version }}.tar.gz
  sha256: fb93c22659d8910168197e2c69693dffb49cc84e09b937fd3764a2aac7c757fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - networkx
    - numpy
    - pandas
    - python >=3.8

test:
  imports:
    - napari_graph
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/napari/napari-graph
  summary: Efficient graph data structures and algorithms for fast slicing, visualization, and editing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DragaDoncila
    - goanpeca
    - jaimergp
    - kephale
    - kevinyamauchi
