{% set name = "napari-graph" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-graph-{{ version }}.tar.gz
  sha256: 218837c6f7d200beb0762f39ea95903a78501f843713bf320981abcd9fb08232

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - networkx
    - numba
    - numpy
    - pandas
    - python >=3.8,<3.11

test:
  imports:
    - napari_graph
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-graph
  summary: Efficient graph data structures and algorithms for fast slicing, visualization, and editing
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/napari/napari-graph

extra:
  recipe-maintainers:
    - DragaDoncila
    - goanpeca
    - jaimergp
    - kephale
    - kevinyamauchi
